export function renderPrice(prop) {
  if (!prop) return '별도 문의';
  if (!prop.price && !prop.deposit && !prop.monthlyRent) return '별도 문의';

  const tx = prop.transactionType?.[0];
  const fmt = (n) => (n ? `${n.toLocaleString()}만` : '0만');

  if (tx === '월세')
    return `보증금 ${fmt(prop.deposit)} / 월 ${fmt(prop.monthlyRent)} / 관리비 ${fmt(prop.maintenanceFee)}`;
  if (tx === '전세') return `전세 ${fmt(prop.deposit)}원`;
  if (tx === '매매') return `매매 ${fmt(prop.price)}원`;
  if (tx === '임대')
    return prop.deposit
      ? `보증금 ${fmt(prop.deposit)} / 월 ${fmt(prop.monthlyRent)}`
      : '별도 문의';
  return '별도 문의';
}

export function getTypeBadgeStyle(type) {
  const map = {
    아파트: { bg: '#f5ede3', color: '#8b5e3c' },
    빌라: { bg: '#f5ede3', color: '#8b5e3c' },
    원룸: { bg: '#fdf3e7', color: '#b07028' },
    오피스텔: { bg: '#fdf3e7', color: '#b07028' },
    주택: { bg: '#f5ede3', color: '#8b5e3c' },
    상가: { bg: '#f0f4f8', color: '#3d5a80' },
    빌딩: { bg: '#2c2c2c', color: '#c19a6b' },
    토지: { bg: '#e8f5e9', color: '#2e7d32' },
    건물: { bg: '#f3e5f5', color: '#6a1b9a' },
  };
  return map[type] || { bg: '#f4f4f4', color: '#555' };
}

export const mockProperties = [
  {
    id: 'mock-1',
    name: '대연동 신축 아파트',
    propertyNumber: 'PROP-001',
    type: '아파트',
    transactionType: ['매매'],
    status: 'Available',
    price: 55000,
    deposit: 0,
    monthlyRent: 0,
    maintenanceFee: 0,
    address: '부산광역시 남구 대연동 123',
    area: 84,
    exclusiveArea: 72,
    totalFloors: 20,
    currentFloor: 12,
    direction: '남향',
    totalParking: '가능',
    isExposed: true,
    isRecommended: true,
    imageUrl: '',
    imageUrls: [],
    features: '신축 아파트, 역세권, 학군 우수',
    blogUrl: 'https://blog.naver.com/zsaza',
    hitCount: 120,
    createdAt: '2026-01-15T00:00:00.000Z',
  },
  {
    id: 'mock-2',
    name: '대연동 오피스텔 월세',
    propertyNumber: 'PROP-002',
    type: '오피스텔',
    transactionType: ['월세'],
    status: 'Available',
    price: 0,
    deposit: 1000,
    monthlyRent: 65,
    maintenanceFee: 10,
    address: '부산광역시 남구 대연동 456',
    area: 33,
    exclusiveArea: 28,
    totalFloors: 15,
    currentFloor: 7,
    direction: '동향',
    totalParking: '가능',
    isExposed: true,
    isRecommended: false,
    imageUrl: '',
    imageUrls: [],
    features: '풀옵션, 관리비 포함 인터넷/수도',
    blogUrl: '',
    hitCount: 85,
    createdAt: '2026-02-10T00:00:00.000Z',
  },
  {
    id: 'mock-3',
    name: '대연동 원룸 전세',
    propertyNumber: 'PROP-003',
    type: '원룸',
    transactionType: ['전세'],
    status: 'Available',
    price: 0,
    deposit: 8000,
    monthlyRent: 0,
    maintenanceFee: 5,
    address: '부산광역시 남구 대연동 789',
    area: 22,
    exclusiveArea: 18,
    totalFloors: 5,
    currentFloor: 3,
    direction: '남향',
    totalParking: '불가',
    isExposed: true,
    isRecommended: true,
    imageUrl: '',
    imageUrls: [],
    features: '에어컨, 세탁기, 냉장고 포함',
    blogUrl: '',
    hitCount: 60,
    createdAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'mock-4',
    name: '대연동 상가 임대',
    propertyNumber: 'PROP-004',
    type: '상가',
    transactionType: ['임대'],
    status: 'Available',
    price: 0,
    deposit: 5000,
    monthlyRent: 150,
    maintenanceFee: 20,
    address: '부산광역시 남구 대연동 321',
    area: 66,
    exclusiveArea: 60,
    totalFloors: 4,
    currentFloor: 1,
    direction: '',
    totalParking: '가능',
    isExposed: true,
    isRecommended: false,
    imageUrl: '',
    imageUrls: [],
    features: '1층 코너 상가, 유동인구 많음',
    blogUrl: '',
    hitCount: 45,
    createdAt: '2026-03-15T00:00:00.000Z',
  },
  {
    id: 'mock-5',
    name: '대연동 토지 매매',
    propertyNumber: 'PROP-005',
    type: '토지',
    transactionType: ['매매'],
    status: 'Available',
    price: 120000,
    deposit: 0,
    monthlyRent: 0,
    maintenanceFee: 0,
    address: '부산광역시 남구 대연동 654',
    area: 200,
    exclusiveArea: 200,
    totalFloors: 0,
    currentFloor: '',
    direction: '',
    totalParking: '',
    isExposed: true,
    isRecommended: true,
    imageUrl: '',
    imageUrls: [],
    features: '주거지역, 개발 가능, 도로 접면',
    blogUrl: '',
    hitCount: 30,
    createdAt: '2026-04-01T00:00:00.000Z',
  },
];
