export const DEFAULT_FIELDS = [
  { id: 'property_id',    label: '매물고유번호',             type: 'auto',           colSpan: 1, hint: '자동 생성' },
  { id: 'recommended',   label: '추천매물',                 type: 'checkbox',       colSpan: 1, hint: '메인페이지 추천 노출' },
  { id: 'contract_status', label: '계약상태', type: 'select', colSpan: 1, options: ['계약가능','계약진행중','계약완료'], hint: '계약가능만 공개 노출' },
  { id: 'title',         label: '매물제목/특징',            type: 'text',           colSpan: 2 },
  { id: 'category',      label: '매물분류',                 type: 'radio',          colSpan: 2, options: ['다세대', '연립', '빌라', '상가주택'] },
  { id: 'transaction',   label: '거래종류',                 type: 'fixed',          value: '매매' },
  { id: 'location',      label: '소재지',                   type: 'locationPrivacy' },
  { id: 'address_detail', label: '상세주소',                type: 'locationPrivacy', placeholder: '상세주소 입력' },
  { id: 'address_public', label: '지번노출여부',            type: 'radio',          colSpan: 1, options: ['노출', '미노출'] },
  { id: 'map_config',    label: '지도 설정',                type: 'mapConfig' },
  { id: 'building_type', label: '건물유형',                 type: 'radio',          colSpan: 2, options: ['건물전체', '건물일부'] },
  { id: 'supply_area',   label: '공급면적 (㎡)',            type: 'number',         colSpan: 1 },
  { id: 'exclusive_area', label: '전용면적 (㎡)',           type: 'number',         colSpan: 1 },
  { id: 'land_share_area', label: '대지지분 (㎡)',          type: 'number',         colSpan: 1 },
  { id: 'sale_price',    label: '매매가격 (만원)',          type: 'number',         colSpan: 1 },
  { id: 'curr_deposit',  label: '현보증금 (만원)',          type: 'number',         colSpan: 1 },
  { id: 'curr_monthly',  label: '현월세 (만원)',            type: 'number',         colSpan: 1 },
  { id: 'maintenance',   label: '관리비 (만원)',            type: 'number',         colSpan: 1 },
  { id: 'loan_info',     label: '융자금 (만원)',            type: 'number',         colSpan: 1 },
  { id: 'move_in',       label: '입주가능일',               type: 'text',           colSpan: 1 },
  { id: 'curr_floor',    label: '해당 층',                  type: 'privacyText' },
  { id: 'total_floors',  label: '총 층수',                  type: 'number',         colSpan: 1 },
  { id: 'rooms',         label: '방 수',                    type: 'number',         colSpan: 1 },
  { id: 'bathrooms',     label: '욕실 수',                  type: 'number',         colSpan: 1 },
  { id: 'direction',     label: '기준/방향',                type: 'direction',      colSpan: 2 },
  { id: 'households',    label: '세대가구수',               type: 'number',         colSpan: 1 },
  { id: 'entrance_type', label: '현관유형',                 type: 'radio',          colSpan: 1, options: ['복도식', '계단식', '복합식'] },
  { id: 'room_type',     label: '방거실형태',               type: 'radio',          colSpan: 1, options: ['오픈형', '분리형'] },
  { id: 'duplex',        label: '복층여부',                 type: 'radio',          colSpan: 1, options: ['단층', '복층'] },
  { id: 'parking_yn',    label: '주차가능여부',             type: 'radio',          colSpan: 1, options: ['주차가능', '주차불가능'] },
  { id: 'total_parking', label: '총 주차대수',              type: 'number',         colSpan: 1 },
  { id: 'illegal_building', label: '위반건축물여부',        type: 'radio',          colSpan: 1, options: ['해당없음', '위반건축물'] },
  { id: 'building_use',  label: '건물용도',                 type: 'text',           colSpan: 2 },
  { id: 'approval_date', label: '사용승인일',               type: 'text',           colSpan: 1 },
  { id: 'heating_type',  label: '난방시설',                 type: 'radio',          colSpan: 2, options: ['개별난방', '중앙난방', '지역난방'] },
  { id: 'heating_fuel',  label: '난방연료',                 type: 'radio',          colSpan: 2, options: ['도시가스', '열병합', '기름', '심야전기', '태양열', 'LPG', '전기', '지열'] },
  { id: 'photos',        label: '사진정보',                 type: 'photos',         colSpan: 3 },
  { id: 'opt_ac',       label: '에어컨',    type: 'multicheck', colSpan: 3, options: ['벽걸이에어컨', '스탠드에어컨', '전장에어컨'] },
  { id: 'opt_general',  label: '일반옵션',  type: 'multicheck', colSpan: 3, options: ['침대', '책상', '옷장', '붙박이장', '신발장', '소파', 'TV', '샤워부스', '욕조', '비데', '세탁기', '건조기', '식탁', '냉장고', '싱크대', '식기세척기', '가스레인지', '전기레인지', '인덕션레인지', '전자레인지', '가스오븐'] },
  { id: 'opt_security', label: '보안옵션',  type: 'multicheck', colSpan: 3, options: ['경비원', '비디오폰', '인터폰', '카드키', 'CCTV', '사설경비', '현관보안', '방범창'] },
  { id: 'opt_extra',    label: '기타옵션',  type: 'multicheck', colSpan: 3, options: ['엘리베이터', '화재경보기', '베란다', '테라스', '마당', '무인택배함'] },
  { id: 'opt_parking',  label: '주차옵션',  type: 'multicheck', colSpan: 2, options: ['자주식주차', '기계식주차'] },
  { id: 'description',  label: '매물 상세정보', type: 'textarea', colSpan: 3 },
];

export const FIELD_TYPES = [
  { type: 'text',       label: '텍스트 입력',    icon: '✏️' },
  { type: 'number',     label: '숫자 입력',      icon: '🔢' },
  { type: 'select',     label: '드롭다운',        icon: '▾' },
  { type: 'radio',      label: '라디오 버튼',    icon: '⊙' },
  { type: 'multicheck', label: '체크박스 그룹',  icon: '☑️' },
  { type: 'textarea',   label: '텍스트에어리어', icon: '📝' },
  { type: 'checkbox',   label: '단일 체크박스',  icon: '✅' },
];
