export const DEFAULT_FIELDS = [
  { id: 'property_id',           label: '매물고유번호',                    type: 'auto',       colSpan: 1, hint: '자동 생성' },
  { id: 'recommended',           label: '추천매물',                        type: 'checkbox',   colSpan: 1, hint: '메인페이지 추천 노출' },
  { id: 'contract_status', label: '계약상태', type: 'select', colSpan: 1, options: ['계약가능','계약진행중','계약완료'], hint: '계약가능만 공개 노출' },
  { id: 'title',                 label: '매물제목/특징',                   type: 'text',       colSpan: 2, hint: '메인카드·리스트에서 제목으로 표시' },
  { id: 'category',              label: '매물분류',                        type: 'fixed',      value: '오피스텔' },
  { id: 'transaction',           label: '거래종류',                        type: 'fixed',      value: '전세' },
  { id: 'building_use_category', label: '건축물용도_분류',                  type: 'radio',      colSpan: 1, options: ['주거용', '업무용'] },
  { id: 'location',              label: '소재지',                          type: 'locationPrivacy', placeholder: '동까지 기입' },
  { id: 'address_detail',        label: '상세주소',                        type: 'locationPrivacy', placeholder: '상세주소 입력' },
  { id: 'map_config',            label: '지도 설정',                       type: 'mapConfig' },
  { id: 'ofc_name',              label: '오피스텔명',                       type: 'text',       colSpan: 2 },
  { id: 'pyeong',                label: '평형',                            type: 'text',       colSpan: 1 },
  { id: 'ho',                    label: '호수',                            type: 'privacyText' },
  { id: 'supply_area',           label: '공급면적(㎡)',                     type: 'number',     colSpan: 1 },
  { id: 'exclusive_area',        label: '전용면적(㎡)',                     type: 'number',     colSpan: 1 },
  { id: 'jeonse_price',          label: '전세가격 (만원)',                   type: 'number',     colSpan: 1 },
  { id: 'maintenance',           label: '관리비 (만원)',                     type: 'number',     colSpan: 1 },
  { id: 'loan_info',             label: '융자금 정보 (만원)',                type: 'number',     colSpan: 1 },
  { id: 'move_in',               label: '입주가능일',                       type: 'text',       colSpan: 1 },
  { id: 'curr_floor',            label: '해당 층',                         type: 'text',       colSpan: 1 },
  { id: 'total_floors',          label: '총 층수',                         type: 'number',     colSpan: 1 },
  { id: 'rooms',                 label: '방 수',                           type: 'number',     colSpan: 1 },
  { id: 'bathrooms',             label: '욕실 수',                         type: 'number',     colSpan: 1 },
  { id: 'direction',             label: '기준/방향',                       type: 'direction',  colSpan: 2, hint: '기준 입력 + 방향 선택' },
  { id: 'entrance',              label: '현관유형',                        type: 'radio',      colSpan: 1, options: ['복도식', '계단식', '복합식'] },
  { id: 'duplex',                label: '복층여부',                        type: 'radio',      colSpan: 1, options: ['단층', '복층'] },
  { id: 'parking_yn',            label: '주차가능여부',                    type: 'radio',      colSpan: 1, options: ['주차가능', '주차불가능'] },
  { id: 'total_parking',         label: '총 주차대수',                     type: 'number',     colSpan: 1 },
  { id: 'unit_parking',          label: '세대당 주차대수',                 type: 'number',     colSpan: 1 },
  { id: 'approval_date',         label: '사용검사일/사용승인일/준공일',      type: 'text',       colSpan: 2 },
  { id: 'building_use_text',     label: '건축물용도(상세)',                 type: 'text',       colSpan: 1 },
  { id: 'description',           label: '매물 상세정보',                   type: 'textarea',   colSpan: 3 },
  { id: 'photos',                label: '사진정보',                        type: 'photos',     colSpan: 3, hint: '기존 Cloudinary 연결방식 유지' },
  { id: 'opt_ac',       label: '에어컨',    type: 'multicheck', colSpan: 3, options: ['벽걸이에어컨', '스탠드에어컨', '전장에어컨'] },
  { id: 'opt_general',  label: '일반옵션',  type: 'multicheck', colSpan: 3, options: ['침대', '책상', '옷장', '붙박이장', '신발장', '소파', 'TV', '샤워부스', '욕조', '비데', '세탁기', '건조기', '식탁', '냉장고', '싱크대', '식기세척기', '가스레인지', '전기레인지', '인덕션레인지', '전자레인지', '가스오븐'] },
  { id: 'opt_security', label: '보안옵션',  type: 'multicheck', colSpan: 3, options: ['경비원', '비디오폰', '인터폰', '카드키', 'CCTV', '사설경비', '현관보안', '방범창'] },
  { id: 'opt_extra',    label: '기타옵션',  type: 'multicheck', colSpan: 3, options: ['엘리베이터', '화재경보기', '베란다', '테라스', '마당', '무인택배함'] },
  { id: 'opt_parking',  label: '주차옵션',  type: 'multicheck', colSpan: 2, options: ['자주식주차', '기계식주차'] },
];

export const FIELD_TYPES = [
  { type: 'text',       label: '텍스트 입력',   icon: '✏️' },
  { type: 'number',     label: '숫자 입력',     icon: '🔢' },
  { type: 'select',     label: '드롭다운',       icon: '▾' },
  { type: 'radio',      label: '라디오 버튼',   icon: '⊙' },
  { type: 'multicheck', label: '체크박스 그룹', icon: '☑️' },
  { type: 'textarea',   label: '텍스트에어리어', icon: '📝' },
  { type: 'checkbox',   label: '단일 체크박스', icon: '✅' },
];
