export const DEFAULT_FIELDS = [
  { id: 'property_id',       label: '매물고유번호',             type: 'auto',       colSpan: 1, hint: '자동 생성' },
  { id: 'recommended',       label: '추천매물',                 type: 'checkbox',   colSpan: 1, hint: '메인페이지 추천 노출' },
  { id: 'contract_status', label: '계약상태', type: 'select', colSpan: 1, options: ['계약가능','계약진행중','계약완료'], hint: '계약가능만 공개 노출' },
  { id: 'title',             label: '매물제목/특징',            type: 'text',       colSpan: 2 },
  { id: 'category',          label: '매물분류',                 type: 'fixed',      value: '토지' },
  { id: 'sub_category',      label: '세부지목',                 type: 'radio',      colSpan: 3, options: ['대', '전', '답', '임야', '공장용지', '과수원', '잡종지', '목장용지', '창고용지', '주차장', '주유소용지', '종교용지', '묘지', '도로', '구거', '유지', '염전', '하천', '유원지', '학교용지', '체육용지', '양어장', '광천지', '철도용지', '공원', '수도용지', '제방', '사적지', '기타'] },
  { id: 'transaction',       label: '거래종류',                 type: 'fixed',      value: '월세' },
  { id: 'location',          label: '소재지',                   type: 'locationPrivacy' },
  { id: 'address_detail',    label: '상세주소',                 type: 'locationPrivacy', placeholder: '상세주소 입력' },
  { id: 'address_public',    label: '지번노출여부',             type: 'radio',      colSpan: 1, options: ['노출', '미노출'] },
  { id: 'map_config',        label: '지도 설정',                type: 'mapConfig' },
  { id: 'land_area',         label: '대지면적 (㎡)',            type: 'number',     colSpan: 1 },
  { id: 'deposit',           label: '보증금 (만원)',            type: 'number',     colSpan: 1 },
  { id: 'monthly_rent',      label: '월세 (만원)',              type: 'number',     colSpan: 1 },
  { id: 'monthly_fee',       label: '월관리비 (만원)',          type: 'number',     colSpan: 1 },
  { id: 'loan_info',         label: '융자금 (만원)',            type: 'number',     colSpan: 1 },
  { id: 'move_in',           label: '입주가능일',               type: 'text',       colSpan: 1 },
  { id: 'curr_floor',        label: '해당 층',                  type: 'privacyText' },
  { id: 'above_floors',      label: '지상 층수',                type: 'number',     colSpan: 1 },
  { id: 'rooms',             label: '방 수',                    type: 'number',     colSpan: 1 },
  { id: 'bathrooms',         label: '욕실 수',                  type: 'number',     colSpan: 1 },
  { id: 'direction',         label: '기준/방향',                type: 'direction',  colSpan: 2 },
  { id: 'parking_yn',        label: '주차가능여부',             type: 'radio',      colSpan: 1, options: ['주차가능', '주차불가능'] },
  { id: 'total_parking',     label: '총 주차대수',              type: 'number',     colSpan: 1 },
  { id: 'current_use',       label: '현재용도',                 type: 'text',       colSpan: 2 },
  { id: 'recommended_use',   label: '추천용도',                 type: 'text',       colSpan: 2 },
  { id: 'zoning',            label: '용도지역',                 type: 'text',       colSpan: 1 },
  { id: 'national_land_use', label: '국토이용',                 type: 'radio',      colSpan: 1, options: ['있음', '없음'] },
  { id: 'city_planning',     label: '도시계획',                 type: 'radio',      colSpan: 1, options: ['있음', '없음'] },
  { id: 'building_permit',   label: '건축허가',                 type: 'radio',      colSpan: 1, options: ['있음', '없음'] },
  { id: 'land_trade_permit', label: '토지거래허가',             type: 'radio',      colSpan: 1, options: ['있음', '없음'] },
  { id: 'access_road',       label: '진입도로',                 type: 'radio',      colSpan: 1, options: ['있음', '없음'] },
  { id: 'inspection_date',   label: '사용검사일/사용승인일/준공일', type: 'text',  colSpan: 1 },
  { id: 'description',       label: '매물 상세정보',            type: 'textarea',   colSpan: 3 },
  { id: 'photos',            label: '사진정보',                 type: 'photos',     colSpan: 3 },
];

export const FIELD_TYPES = [
  { type: 'text',       label: '텍스트 입력',   icon: '✏️' },
  { type: 'number',     label: '숫자 입력',     icon: '🔢' },
  { type: 'select',     label: '드롭다운',       icon: '▾' },
  { type: 'radio',      label: '라디오 버튼',   icon: '⊙' },
  { type: 'multicheck', label: '체크박스 그룹', icon: '☑️' },
  { type: 'textarea',   label: '텍스트에어리어', icon: '📝' },
  { type: 'checkbox',   label: '단일 체크박스', icon: '✅' },
];
